### ISSUE TITLE
Pulling application should show an error if not container can be found for the system architecture

### ISSUE THREAD

**Issue by axel7083** [projectatomic/studio-extension#114]

**Comment by axel7083** [comment]
For now here is the code filtering the available images based on the system architecture.

https://github.com/projectatomic/studio-extension/blob/984fe48f63a844ec10c92f313b669ab920c51438/packages/backend/src/managers/applicationManager.ts#L134-L136

We do not support letting the user choose _incompatible_ architecture (_for now?_)

**Comment by deboer-tim** [comment]
Thanks. I'd disagree in general, but in this context if 'we're providing architecture-specific models for all platforms they should run on' I guess that's fine.
