### ISSUE TITLE
Start the pod with sample app and model service 

### ISSUE THREAD

**Issue by lstocchi** [projectatomic/studio-extension#129]
When https://github.com/projectatomic/studio-extension/pull/100 will be merged we are able to create the pod with a sample app and the model service. We should then start it.

The known problem is that if you start the pod it fails because the model service is slower at loading than the sample app. So when the sample app tries to connect to the model service, it fails and it must be restarted singularly when the model service is up.

**Comment by feloy** [comment]
IMO, the app should be able to handle the problem, by retrying to connect. I've created a patch for the sample app: https://github.com/axel7083/locallm/pull/4

**Comment by lstocchi** [comment]
For this approach we could also use the --restart flag when creating the container. Jeff was saying to listen to the port and start the container when we find the model service listening. WDYT? @jeffmaury

**Comment by feloy** [comment]
Having the client trying to reconnect is a best practice for production (see rule in Apps are independent at
https://learnk8s.io/production-best-practices).

IMO it would be nice to encourage the developer to respect this rule
